# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B test --file pom.xml

    - name: Validate Number of Unit Tests
      run: |
        # Extract test summary from Maven output
        TEST_SUMMARY=$(grep -E "Tests run: [0-9]+," maven-test-output.txt | tail -1)
        echo "Test Summary: $TEST_SUMMARY"

        # Extract the number of tests run
        TESTS_RUN=$(echo "$TEST_SUMMARY" | grep -oP "(?<=Tests run: )[0-9]+")
        echo "Tests Run: $TESTS_RUN"

        # Check if the number of tests is at least 40
        if [ "$TESTS_RUN" -lt 40 ]; then
          echo "Not enough tests run: $TESTS_RUN. At least 40 required."
          exit 1
        else
          echo "Sufficient tests run: $TESTS_RUN."
        f